#!/usr/bin/env python3
"""make_requests.py -- build the `klt sim` AC requests for the issue #79 tank A/B.

    make_requests.py <outdir> [--cells N] [--mim-um S] [--candidate NAME]

Writes, per (variant, mos corner, Vctrl): <outdir>/<variant>/<mos>_v<V>/{tank.spice,
request.json} plus a copy of the EM inductor model.  Variants:

  bn-tank   varactor bn tied to the well/tank node W   (pre-#79 schematic)
  bn-sub    varactor bn tied to 0, the p-substrate     (post-#79 schematic)

WHAT THE CIRCUIT IS.  design/vco.spice's passive tank, small-signal:
  XL1/XL2 (EM-fitted inductor, as in the netlist), XC1 (cap_cmim 3.65x3.65 um,
  as in the netlist), and 16 varactor cells per side (as in the netlist).
  The MOS-capacitor CORE of each cell (`nmvcap1/2`, an OSDI/Verilog-A device)
  is replaced by a lumped series R-C taken from the committed varactor record
  (sim/varactor-characterization/records/20260927-081226-f88eb89.csv,
  mos_small = w 3.74u / l 0.3u / Nx 1, the netlist's geometry, 5 GHz, 27 C):
  C = c_5ghz_f, R = 1/(2 pi 5e9 C q_5ghz).  EVERYTHING ELSE in the cell is
  the PDK subcircuit's own text, copied verbatim from
  sg13g2_svaricaphv_mod.lib: the well-to-substrate diode `dsubw`, its
  series `rsubw`, and its `.model dsubw d` card.  Only the `bn` connection
  differs between the two variants -- exactly the edit #79 makes.
  The record's own measurement tied W and bn together, so its C and Q are the
  cell WITHOUT the junction; the junction branch is therefore added by the
  native diode, not double counted.
"""
import argparse, json, os, shutil, sys

# Defaults are the design/vco.spice sizing (16 cells/side, 3.65 um MIM) and
# reproduce the original #79 decks byte-for-byte.  --cells/--mim-um/--candidate
# (issue #93) emit ONE bn=substrate variant named NAME at the given sizing and
# skip the bn-tank and tnom supplements.  The cell R-C is the same mos_small
# record value per cell, so cell scaling is an ASSUMPTION (see README).
_ap = argparse.ArgumentParser()
_ap.add_argument("outdir")
_ap.add_argument("--cells", type=int, default=16)
_ap.add_argument("--mim-um", type=float, default=3.65)
_ap.add_argument("--candidate", default=None)
_args = _ap.parse_args()
if _args.cells < 1 or _args.mim_um < 1.14:
    sys.exit("illegal sizing: need cells >= 1 and mim side >= 1.14 um (cmim_minLW)")
if _args.candidate and "__" in _args.candidate:
    sys.exit("candidate name must not contain '__'")
if _args.candidate is None and (_args.cells, _args.mim_um) != (16, 3.65):
    sys.exit("non-default sizing requires --candidate NAME")
out = _args.outdir
NCELLS = _args.cells
MIM_STR = "%ge-6" % _args.mim_um
repo = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# (c_5ghz_f, q_5ghz) at 27 C from the varactor record, key (mos corner, V_rec)
REC = {("tt", 3.3): (1.045e-14, 44.79), ("tt", 1.8): (5.63e-15, 83.98),
       ("tt", 0.0): (5.569e-15, 84.92)}
# NOTE: the record's control voltage V_rec is applied to the WELL with the gates
# at 0 V.  In the netlist the gates sit at Vctrl and the well at 3.3 V, so
# V_rec = 3.3 - Vctrl.  Vctrl 0.0 -> V_rec 3.3 ; 1.5 -> 1.8 ; 3.3 -> 0.0.
# The record rows below are (C5, Q5) read straight from the csv.
CSV = os.path.join(repo, "sim/varactor-characterization/records/20260927-081226-f88eb89.csv")
rows = {}
for ln in open(CSV).read().splitlines()[1:]:
    f = ln.split(",")
    if f[0] == "mos" and f[1] == "small" and f[3] == "27":
        rows[(f[2], round(float(f[4]), 2))] = (float(f[8]), float(f[12]))
import math
W5 = 2 * math.pi * 5e9
VCTRL_TO_VREC = {0.0: 3.3, 1.5: 1.8, 3.3: 0.0}
# (mos corner, Vctrl) set: tt at three Vctrl; ss/ff at band-centre Vctrl 1.5
POINTS = [("tt", 0.0), ("tt", 1.5), ("tt", 3.3), ("ss", 1.5), ("ff", 1.5)]

IND = open(os.path.join(repo, "sim/inductor-model/sg13g2_inductor_em.spice")).read()

def deck(variant, c, r, vc, tnom=None):
    TNOM = f" tnom = {tnom}  $ WORKAROUND, NOT the PDK card: stops vj(T) scaling" if tnom is not None else ""
    bn = "W" if variant == "bn-tank" else "0"
    cells = []
    for side, node in (("P", "OUTP"), ("N", "OUTN")):
        for i in range(1, NCELLS + 1):
            # subckt pins: G W bn   (bn connection is THE variable under test)
            cells.append(f"XCV{side}{i} VCTRL {node} {'%s' % node if variant == 'bn-tank' else '0'} svar")
    return f"""* tank A/B for issue #79 -- variant {variant}: varactor bn -> {'W (tank node)' if bn == 'W' else '0 (p-substrate)'}
* generated by sim/bn-substrate-tank/make_requests.py; see its docstring
* sim/inductor-model/sg13g2_inductor_em.spice, INLINED below (klt 0.6.0's batch
* backend does not stage .include targets)
{IND}
* PDK svaricap well parasitics, verbatim from sg13g2_svaricaphv_mod.lib,
* around a lumped R-C standing in for the OSDI MOS core (see make_requests.py)
.model dsubw d is = 2.45E-17 jsw = 5.959E-10 n = 4 ns = 1.029 cjo = 1.444E-15 vj = 0.1 m = 0.1052 cjp = 1.117E-09 php = 0.457 mjsw = 0.2595 fc = 0.95 cta = 1E-06{TNOM}
.subckt svar G W bn
.param l=0.3e-6 w=3.74e-6 Nx=1 Ny=1
.param rsubw0=0.2596 rsubwf=0.0009212 rsubwexp=0.6952
Rcore W n1 {r:.6g}
Ccore n1 G {c:.6g}
dsubw W1 W dsubw off area = '(((Nx*0.38u)+(Nx*l))+1.11u)*(Ny*(w+0.97u))' pj = '2*((((Nx*0.38u)+(Nx*l))+1.11u)+(Ny*(w+0.97u)))'
rsubw W1 bn r = '(rsubw0/(sqrt(pow(Nx, rsubwexp))))/(w+rsubwf)'
.ends svar
VDD VDD 0 dc 3.3
VCT VCTRL 0 dc {vc}
XL1 VDD OUTP 0 inductor w=8.22e-6 s=3.74e-6 d=141.975e-6 nr_r=4 m=1
XL2 VDD OUTN 0 inductor w=8.22e-6 s=3.74e-6 d=141.975e-6 nr_r=4 m=1
XC1 OUTP OUTN cap_cmim w={MIM_STR} l={MIM_STR} m=1
{chr(10).join(cells)}
* AC probe: 1 A differential current, so v(zd) IS the differential impedance
Iac OUTN OUTP dc 0 ac 1
Ezd ZD 0 OUTP OUTN 1
Rzd ZD 0 1G
"""

def request(vc, temps=(-40, 27, 125)):
    meas = [
     ("zpk", "ohm", ".meas ac zpk MAX vm(zd) FROM=1g TO=12g"),
     ("f0", "Hz", ".meas ac f0 WHEN vp(zd)=0 FALL=1"),
     ("f_p45", "Hz", ".meas ac f_p45 WHEN vp(zd)=0.78539816 FALL=1"),
     ("f_m45", "Hz", ".meas ac f_m45 WHEN vp(zd)=-0.78539816 FALL=1"),
    ]
    return {"netlist": "tank.spice", "engine": "ngspice",
            "models": {"pdk": "ihp-sg13g2", "lib": "libs.tech/ngspice/models/cornerCAP.lib"},
            "corners": {"process": [{"name": s, "sections": [s]} for s in ("cap_typ", "cap_bcs", "cap_wcs")],
                        "temperature_c": list(temps)},
            "analysis": {"kind": "ac", "args": "lin 5501 1g 12g"},
            "measurements": [{"name": a, "unit": u, "spice": s} for a, u, s in meas],
            "options": {"timeout_s": 900, "keep_artifacts": True,
                        "ngspice_init": ["set ngbehavior=hsa"]}}

def emit(name, variant, mos, vc, temps, tnom=None):
    c, q = rows[(mos, VCTRL_TO_VREC[vc])]
    r = 1.0 / (W5 * c * q)
    d = os.path.join(out, name, f"{mos}_v{vc}")
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, "tank.spice"), "w").write(deck(variant, c, r, vc, tnom))
    json.dump(request(vc, temps), open(os.path.join(d, "request.json"), "w"), indent=2)
    json.dump({"variant": name, "mos": mos, "vctrl": vc, "c_cell_f": c, "q5": q,
               "r_cell_ohm": r, "dsubw_tnom": tnom,
               "cells_per_side": NCELLS, "mim_side_um": _args.mim_um,
               "source": "sim/varactor-characterization/records/20260927-081226-f88eb89.csv mos small 27C"},
              open(os.path.join(d, "cell.json"), "w"), indent=2)

if _args.candidate:
    for mos, vc in POINTS:
        emit(_args.candidate, "bn-sub", mos, vc, (-40, 27, 125))
    print("ok", out)
    sys.exit(0)
for variant in ("bn-tank", "bn-sub"):
    for mos, vc in POINTS:
        emit(variant, variant, mos, vc, (-40, 27, 125))
# flagged workaround supplement (bn-sub only): the shipped dsubw card goes NaN
# above ~52 C (vj = 0.1 V scales negative); tnom pinned to the run temperature
for mos, vc in POINTS:
    emit("bn-sub-tnom125", "bn-sub", mos, vc, (125,), 125)
emit("bn-sub-tnom85", "bn-sub", "tt", 1.5, (85,), 85)
print("ok", out)
