#!/usr/bin/env python3
"""surrogate_bench.py -- isolated single-point bench for the OSDI-free varactor
surrogate (issue #179).   SCREENING ONLY -- grades no specification row.

One invocation = ONE ngspice transient (a single unit; never a grid):

    surrogate_bench.py --point pre79      # bn tied to W: known-answer vs the pilot
    surrogate_bench.py --point corrected  # bn on 0 (design/vco.spice): smoke only

pre79      Recreates the pre-#79 topology (each cell's bn on its own well W) at
           tt / cap_typ / hbt_typ / 27 C / VCTRL = 1.65 V and compares f_osc and
           the differential Vpp with the committed pilot row
           records/20260926-010627-e391693-pilot.csv under the tolerance
           formulas FIXED by issue #179.  The tolerances are computed and
           printed BEFORE the simulator is started, and are never changed after.
corrected  The corrected topology (bn on 0) at the same corner and VCTRL.
           Proves startup and model integration only; it is NOT compared with
           the pre-#79 frequency as though the topologies were equivalent.

Both report f_osc / Vpp and the minimum / maximum INSTANTANEOUS v_rec at the
behavioral core (V(core node) - V(VCTRL)) over the whole run.  Outside
[0, 3.3] V +/- 1 mV the run is INVALID-OUT-OF-DOMAIN: no oscillator number is
written, the record carries only the status and the extrema, and the exit code
is 3.  A known-answer FAIL is kept as evidence (record written, exit 1).

Not implemented here, by design: fleet grids, tuning sweeps, ISF / phase noise.
The production OSDI deck (design/vco.spice, osc_bench.sh) is not touched.

Estimator: sim/lib.sh osc_metrics (rising crossings of V(OUTP)-V(OUTN) through
the window's trapezoidal mean, interpolated crossing times, first-to-last
period), the same code the pilot used.
"""
import argparse
import csv
import datetime
import hashlib
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "sim", "tools"))
import svaricap_surrogate as sur  # noqa: E402

PILOT_CSV = "sim/oscillator-core/records/20260926-010627-e391693-pilot.csv"
PILOT_ROW = "pilot_tt_cap_typ_hbt_typ_27c_1.65v"
IND_MODEL = "sim/inductor-model/sg13g2_inductor_em.spice"
# Same transient settings as the pilot (osc_bench.sh): tran 1p 5n 0 2p, window 2.5..5 ns.
TSTEP, TSTOP, TMAX = "1p", "5n", "2p"
TMEAS_START, TSTOP_S = 2.5e-9, 5e-9
SETTLE_FRAC = 0.9


def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()


def models_dir():
    d = os.environ.get("SG13G2_NGSPICE_MODELS")
    if d and os.path.isdir(d):
        return d
    root = os.environ.get("PDK_ROOT") or os.path.expanduser("~/share/pdk")
    d = os.path.join(root, os.environ.get("PDK", "ihp-sg13g2"), "libs.tech/ngspice/models")
    if not os.path.isdir(d):
        raise sur.SurrogateError("no SG13G2 ngspice models under %s (set PDK_ROOT)" % d)
    return d


def lib_sh(fn, *args):
    """Call a sim/lib.sh awk extractor (the same code the pilot used)."""
    r = sh(["bash", "-c", 'source "$1"; shift; "$@"', "_", os.path.join(REPO, "sim/lib.sh"), fn] + list(args))
    if r.returncode != 0:
        raise sur.SurrogateError("sim/lib.sh %s failed: %s" % (fn, r.stderr.strip()))
    return r.stdout.split()


def render_deck(series, topology, vctrl, temp_c, mdir, out_prefix):
    with open(os.path.join(REPO, "design/vco.spice")) as fh:
        body = sur.surrogate_vco_body(fh.read(), "sg13_hv_svaricap_sur", topology)
    body, n = re.subn(r"(?m)^VCT VCTRL 0 dc \S+$", "VCT VCTRL 0 dc %s" % vctrl, body)
    if n != 1:
        raise sur.SurrogateError("expected exactly one VCT source in design/vco.spice, found %d" % n)
    with open(os.path.join(REPO, IND_MODEL)) as fh:
        ind = fh.read()
    return "\n".join([
        "* surrogate_bench: %s   %s" % (sur.LABEL, topology),
        "* GENERATED by sim/oscillator-core/surrogate_bench.py (issue #179); the 32 OSDI",
        "* sg13_hv_svaricap cells of design/vco.spice are replaced by sim/tools/svaricap_surrogate.py",
        ".lib %s/cornerHBT.lib hbt_typ" % mdir,
        ".lib %s/cornerCAP.lib cap_typ" % mdir,
        "* inductor model (inlined): " + IND_MODEL,
        ind,
        "* dsubw card: v0.3.0 text with only vj 0.1 -> 0.3357 (svaricap_overlay.py)",
        sur.render_model_card(),
        sur.render_subckt(series),
        body,
        ".temp %g" % temp_c,
        "Bvdiff VDIFF 0 V = V(OUTP) - V(OUTN)",
        "Rvdiff VDIFF 0 1G",
        ".ic v(OUTP)=3.305 v(OUTN)=3.295",
        ".control",
        "save v(VDIFF) v(OUTP) v(OUTN) v(VCTRL) v(xcvp1.nc) v(xcvp16.nc) v(xcvn1.nc) v(xcvn16.nc)",
        "op",
        "tran %s %s 0 %s" % (TSTEP, TSTOP, TMAX),
        "let w1 = v(VDIFF)",
        "wrdata %s_vdiff w1" % out_prefix,
        "* v_rec at the behavioral core = V(core node) - V(G); G = VCTRL",
        "let w2 = v(xcvp1.nc) - v(VCTRL)",
        "wrdata %s_vrec_p1 w2" % out_prefix,
        "let w3 = v(xcvp16.nc) - v(VCTRL)",
        "wrdata %s_vrec_p16 w3" % out_prefix,
        "let w4 = v(xcvn1.nc) - v(VCTRL)",
        "wrdata %s_vrec_n1 w4" % out_prefix,
        "let w5 = v(xcvn16.nc) - v(VCTRL)",
        "wrdata %s_vrec_n16 w5" % out_prefix,
        ".endc",
        ".end", ""])


def trace_extrema(path):
    vals = []
    with open(path) as fh:
        for ln in fh:
            f = ln.split()
            if len(f) >= 2:
                vals.append(float(f[1]))
    if not vals:
        return float("nan"), float("nan"), 0
    return min(vals), max(vals), len(vals)


def git_info():
    head = sh(["git", "-C", REPO, "rev-parse", "HEAD"]).stdout.strip()
    dirty = sh(["git", "-C", REPO, "diff", "--quiet", "HEAD", "--",
                "sim/tools", "sim/oscillator-core/surrogate_bench.py", "design",
                "sim/varactor-characterization/records"]).returncode != 0
    return head, dirty


def ngspice_version():
    out = sh(["ngspice", "-v"]).stdout
    m = re.search(r"ngspice-(\S+)", out)
    return m.group(0) if m else "unknown"


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--point", required=True, choices=("pre79", "corrected"))
    ap.add_argument("--vctrl", type=float, default=1.65)
    ap.add_argument("--corner", default="tt")
    ap.add_argument("--temp", type=float, default=27.0)
    ap.add_argument("--records-dir", default=os.path.join(HERE, "records"))
    ap.add_argument("--snapshots-dir", default=os.path.join(HERE, "netlist-snapshots"))
    ap.add_argument("--allow-dirty", action="store_true")
    ap.add_argument("--dry-run", action="store_true", help="print tolerances and the deck path only")
    a = ap.parse_args(argv)

    series = sur.load_series(os.path.join(REPO, sur.DEFAULT_CSV))[(a.corner, a.temp)]
    tol = series.tolerances()
    prov = sur.source_provenance()
    head, dirty = git_info()
    if dirty and not a.allow_dirty:
        raise sur.SurrogateError("uncommitted changes under sim/tools, design, the bench or the source CSV; "
                                 "commit first so the record's commit is meaningful (or --allow-dirty)")

    # --- predeclare tolerances BEFORE any simulation -------------------------
    with open(os.path.join(REPO, PILOT_CSV), newline="") as fh:
        pilot = [r for r in csv.DictReader(fh) if r["corner_id"] == PILOT_ROW]
    if len(pilot) != 1:
        raise sur.SurrogateError("pilot row %s not found exactly once" % PILOT_ROW)
    pilot = pilot[0]
    pilot_q = float(pilot["quant_floor_interp_pct"])
    print("predeclared (before the simulator starts): series %s epsilon_C=%.6g epsilon_R=%.6g"
          % (series.key, tol["epsilon_C"], tol["epsilon_R"]))
    print("  tol_dqdv=%.6g tol_R=%.6g; pilot quant_floor_interp_pct=%.6g"
          % (tol["tol_dqdv"], tol["tol_R"], pilot_q))

    # DC pre-check: refuse before simulating if even the DC point is outside the domain
    v0 = sur.vrec_from_vctrl_dc(a.vctrl)
    if sur.classify_domain(v0, v0) != sur.STATUS_OK:
        print(sur.STATUS_INVALID + ": DC v_rec = %g V" % v0, file=sys.stderr)
        return 3

    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d-%H%M%S")
    rid = "%s-%s-surrogate-%s" % (stamp, head[:7], a.point)
    work = tempfile.mkdtemp(prefix="sur179-")
    prefix = os.path.join(work, "w")
    deck = render_deck(series, a.point, a.vctrl, a.temp, models_dir(), prefix)
    deck_path = os.path.join(work, "deck.spice")
    with open(deck_path, "w") as fh:
        fh.write(deck)
    shutil.copy(os.path.join(HERE, ".spiceinit"), os.path.join(work, ".spiceinit"))
    if a.dry_run:
        print("deck:", deck_path)
        return 0

    cmd = ["ngspice", "-b", "deck.spice"]
    r = subprocess.run(cmd, cwd=work, capture_output=True, text=True)
    log = r.stdout + r.stderr
    with open(os.path.join(work, "ngspice.log"), "w") as fh:
        fh.write(log)
    bad = re.search(r"(?im)^.*(unknown subckt|could not find|fatal|doAnalyses: .*(error|aborted)|"
                    r"no such vector|Error:).*$", log)
    if r.returncode != 0 or bad:
        print("ngspice failed (rc=%d): %s" % (r.returncode, bad.group(0) if bad else ""), file=sys.stderr)
        print("scratch kept at", work, file=sys.stderr)
        return 2

    # --- domain: instantaneous v_rec extrema over the WHOLE run ---------------
    ex = [trace_extrema("%s_vrec_%s" % (prefix, k)) for k in ("p1", "p16", "n1", "n16")]
    if any(e[2] == 0 for e in ex):
        print("empty v_rec trace; scratch kept at", work, file=sys.stderr)
        return 2
    vmin, vmax = min(e[0] for e in ex), max(e[1] for e in ex)
    status = sur.classify_domain(vmin, vmax)

    os.makedirs(a.records_dir, exist_ok=True)
    snap = os.path.join(a.snapshots_dir, rid)
    os.makedirs(snap, exist_ok=True)
    shutil.copy(deck_path, os.path.join(snap, "surrogate_%s.spice" % a.point))
    shutil.copy(os.path.join(work, "ngspice.log"), os.path.join(snap, "surrogate_%s.log" % a.point))
    deck_sha = sha256_bytes(deck.encode())
    ver = ngspice_version()

    fields = {"record_id": rid, "point": a.point, "label": sur.LABEL, "status": status,
              "v_rec_min_v": "%.6f" % vmin, "v_rec_max_v": "%.6f" % vmax}
    md = ["# Record %s" % rid, "", "**%s**" % sur.LABEL, "",
          "- **Experiment**: oscillator-core, OSDI-free varactor surrogate (issue #179), point `%s`" % a.point,
          "- **Topology**: " + ("pre-#79 (`bn` tied to each cell's own well W)" if a.point == "pre79"
                                else "corrected (`bn` on 0, as design/vco.spice)"),
          "- **Corner**: MOS fit series `%s/%g C`, cap_typ, hbt_typ, VCTRL = %g V, VDD 3.3 V" % (a.corner, a.temp, a.vctrl),
          "- **Surrogate source**: `%s` (sha256 `%s`, last commit touching it `%s`), mos/small rows, "
          "`c_5ghz_f` and `q_5ghz` columns" % (prov["csv"], prov["csv_sha256"], prov["csv_commit"]),
          "- **Code commit**: `%s`%s" % (head, " (dirty tree, --allow-dirty)" if dirty else ""),
          "- **Command**: `sim/oscillator-core/surrogate_bench.py --point %s --vctrl %g --corner %s --temp %g`; "
          "inner simulator command `%s` (single unit, local)" % (a.point, a.vctrl, a.corner, a.temp, " ".join(cmd)),
          "- **Simulator**: `%s`; transient `tran %s %s 0 %s`, window %g..%g s, start `.ic` 10 mV differential"
          % (ver, TSTEP, TSTOP, TMAX, TMEAS_START, TSTOP_S),
          "- **Rendered deck**: `netlist-snapshots/%s/surrogate_%s.spice` (sha256 `%s`)" % (rid, a.point, deck_sha),
          "- **Model**: charge-based behavioral MOS core (piecewise-linear C, exact piecewise-quadratic "
          "q), pointwise series R = 1/(2 pi 5e9 C Q), exactly one native `dsubw`+`rsubw` branch per cell "
          "with the sanctioned `vj = 0.3357` overlay (`sim/tools/svaricap_overlay.py`); contract in "
          "`sim/tools/svaricap_surrogate.py`.",
          "- " + sur.NOISE_NOTE,
          "- " + sur.PATH_NOTE,
          "- " + sur.FOLLOW_ON_NOTE,
          "- **Limits**: 5 GHz effective C/Q only; fitted bias/corner/temperature/geometry only; "
          "one probe cell per side pair (cells 1 and 16 on each side) stands for the 16 identical cells "
          "of that side; this smoke does not establish broadband or large-grid accuracy.",
          "- **Estimator**: sim/lib.sh `osc_metrics` on V(OUTP)-V(OUTN), rising crossings through the "
          "window mean, interpolated; quantization floor reported per point.",
          "- **Instantaneous v_rec at the core** (whole run, 4 probe cells): min %.6f V, max %.6f V; "
          "domain [0.0, 3.3] V +/- 1 mV -> **%s**" % (vmin, vmax, status), ""]

    rc = 0
    if status != sur.STATUS_OK:
        md += ["## Result", "", "**INVALID-OUT-OF-DOMAIN** -- the surrogate was driven outside its characterized "
               "0.0-3.3 V interval. It refuses to extrapolate: no f_osc / amplitude is reported for this run.", ""]
        rc = 3
    else:
        m = lib_sh("osc_metrics", prefix + "_vdiff", repr(TMEAS_START), repr(TSTOP_S))
        f, vpp, cycles, _av, _x1, _xn, dtmax, nsamp = (float(x) for x in m)
        q_interp = dtmax * f / cycles * 100.0 if cycles else float("nan")
        q_count = 100.0 / cycles if cycles else float("nan")
        st = lib_sh("osc_settle", prefix + "_vdiff", repr(SETTLE_FRAC), repr(TMEAS_START))
        t_settle = st[0]
        fields.update({"f_osc_hz": "%.6e" % f, "vpp_diff_v": "%.6e" % vpp, "cycles": "%d" % cycles,
                       "dt_max_s": "%.3e" % dtmax, "quant_floor_interp_pct": "%.6g" % q_interp,
                       "quant_floor_count_pct": "%.6g" % q_count, "t_settle_s": t_settle})
        started = f > 0 and cycles >= 3
        md += ["## Result", "",
               "- starts and oscillates: **%s**" % ("YES" if started else "NO"),
               "- f_osc = %.6e Hz (%d cycles, interpolated quantization floor %.4g %%, "
               "no-interpolation floor %.4g %%)" % (f, cycles, q_interp, q_count),
               "- differential Vpp = %.6e V; startup settling (0.9 of final envelope) t_settle = %s s"
               % (vpp, t_settle), ""]
        if not started:
            rc = 1
        if a.point == "pre79":
            fp, ap_ = float(pilot["f_osc_hz"]), float(pilot["vpp_diff_v"])
            q_used = max(pilot_q, q_interp)
            kt = sur.known_answer_tolerances(tol["epsilon_C"], tol["epsilon_R"], q_used)
            rf = abs(f - fp) / fp
            ra = abs(vpp - ap_) / ap_
            ok = started and rf <= kt["tol_freq"] and ra <= kt["tol_amp"]
            fields.update({"pilot_f_osc_hz": "%.6e" % fp, "pilot_vpp_diff_v": "%.6e" % ap_,
                           "epsilon_C": "%.6g" % tol["epsilon_C"], "epsilon_R": "%.6g" % tol["epsilon_R"],
                           "quant_floor_used_pct": "%.6g" % q_used,
                           "tol_freq": "%.6g" % kt["tol_freq"], "tol_amp": "%.6g" % kt["tol_amp"],
                           "resid_freq": "%.6g" % rf, "resid_amp": "%.6g" % ra,
                           "known_answer": "PASS" if ok else "FAIL"})
            md += ["## Known-answer comparison against the pilot (fixed formulas of issue #179)", "",
                   "Pilot row `%s` in `%s` (old OSDI netlist, vj = 0.1 unpatched card, pre-#79 topology)." % (PILOT_ROW, PILOT_CSV), "",
                   "| quantity | pilot | surrogate | relative residual | fixed tolerance | verdict |",
                   "|---|---|---|---|---|---|",
                   "| f_osc (Hz) | %.6e | %.6e | %.4f %% | %.4f %% | %s |" % (fp, f, 100 * rf, 100 * kt["tol_freq"], "ok" if rf <= kt["tol_freq"] else "EXCEEDED"),
                   "| differential Vpp (V) | %.6e | %.6e | %.4f %% | %.4f %% | %s |" % (ap_, vpp, 100 * ra, 100 * kt["tol_amp"], "ok" if ra <= kt["tol_amp"] else "EXCEEDED"),
                   "",
                   "Tolerance inputs (computed before the run; leave-one-out on the %s series): "
                   "epsilon_C = %.6g, epsilon_R = %.6g; frequency tolerance = max(1 %%, epsilon_C/2 + "
                   "quant_floor_interp_pct/100) with quant_floor_interp_pct = max(pilot %.6g, this run %.6g) = %.6g; "
                   "amplitude tolerance = max(5 %%, epsilon_C + epsilon_R)."
                   % (series.key, tol["epsilon_C"], tol["epsilon_R"], pilot_q, q_interp, q_used), "",
                   "**Known-answer verdict: %s.** The formulas are fixed by the issue and were not "
                   "widened or tuned after seeing this result." % ("PASS" if ok else "FAIL"), ""]
            if not ok:
                rc = 1
        else:
            md += ["This is the corrected-topology (`bn` on 0) smoke point. It proves startup and model "
                   "integration only and is not compared with the pre-#79 frequency.", ""]

    md_path = os.path.join(a.records_dir, rid + ".md")
    csv_path = os.path.join(a.records_dir, rid + ".csv")
    with open(md_path, "w") as fh:
        fh.write("\n".join(md))
    fields["label"] = sur.LABEL
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(fields))
        w.writeheader()
        w.writerow(fields)
    shutil.rmtree(work, ignore_errors=True)
    print("record:", md_path)
    print({k: fields[k] for k in fields if k not in ("label",)})
    return rc


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except sur.SurrogateError as e:
        print("surrogate_bench: refused: %s" % e, file=sys.stderr)
        sys.exit(1)
