#!/usr/bin/env python3
"""surrogate_bench.py -- isolated single-point bench for the OSDI-free varactor
surrogate (issue #179).   SCREENING ONLY -- grades no specification row.

One invocation = ONE ngspice transient (a single unit; never a grid):

    surrogate_bench.py --point pre79      # bn tied to W: known-answer vs the pilot
    surrogate_bench.py --point corrected  # bn on 0 (design/vco.spice): smoke only

pre79      Recreates the pre-#79 topology (each cell's bn on its own well W) at
           tt / cap_typ / hbt_typ / 27 C / VCTRL = 1.65 V and compares f_osc and
           the differential Vpp with the committed pilot row
           records/20260926-010627-e391693-pilot.csv under the tolerance
           formulas FIXED by issue #179.  The tolerances are computed and
           printed BEFORE the simulator is started, and are never changed after.
corrected  The corrected topology (bn on 0) at the same corner and VCTRL.
           Proves startup and model integration only; it is NOT compared with
           the pre-#79 frequency as though the topologies were equivalent.

Both report f_osc / Vpp and the minimum / maximum INSTANTANEOUS v_rec at the
behavioral core (V(core node) - V(VCTRL)) over the whole run.  Outside
[0, 3.3] V +/- 1 mV the run is INVALID-OUT-OF-DOMAIN: no oscillator number is
written, the record carries only the status and the extrema, and the exit code
is 3.  A malformed / incomplete / non-finite probe trace (a failed measurement,
issue #192: every sample of vdiff and the four probes is validated before any
extrema are taken; coverage tolerances are tied to TMAX) publishes nothing,
keeps the scratch dir and exits 2.  A known-answer FAIL is kept as evidence (record written, exit 1).

Evidence ownership (issue #191): before the simulator starts, a record id is
reserved through sim/lib.sh reserve_record_id (exclusive mkdir under
<parent of --records-dir>/corners/), and the published basename is
<reserved id>-surrogate-<point>.  Custom --records-dir / --snapshots-dir are
checked for that id too, and the deck, log, Markdown and CSV are created
exclusively (never truncating).  A reservation or publication failure exits 1
("refused") and overwrites nothing; a reservation failure writes no evidence.

Not implemented here, by design: fleet grids, tuning sweeps, ISF / phase noise.
The production OSDI deck (design/vco.spice, osc_bench.sh) is not touched.

Estimator: sim/lib.sh osc_metrics (rising crossings of V(OUTP)-V(OUTN) through
the window's trapezoidal mean, interpolated crossing times, first-to-last
period), the same code the pilot used.
"""
import argparse
import csv
import glob
import hashlib
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "sim", "tools"))
import svaricap_surrogate as sur  # noqa: E402

PILOT_CSV = "sim/oscillator-core/records/20260926-010627-e391693-pilot.csv"
PILOT_ROW = "pilot_tt_cap_typ_hbt_typ_27c_1.65v"
IND_MODEL = "sim/inductor-model/sg13g2_inductor_em.spice"
# Same transient settings as the pilot (osc_bench.sh): tran 1p 5n 0 2p, window 2.5..5 ns.
TSTEP, TSTOP, TMAX = "1p", "5n", "2p"  # TMAX_S below must match
TMEAS_START, TSTOP_S = 2.5e-9, 5e-9
SETTLE_FRAC = 0.9


def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()


def models_dir():
    d = os.environ.get("SG13G2_NGSPICE_MODELS")
    if d and os.path.isdir(d):
        return d
    root = os.environ.get("PDK_ROOT") or os.path.expanduser("~/share/pdk")
    d = os.path.join(root, os.environ.get("PDK", "ihp-sg13g2"), "libs.tech/ngspice/models")
    if not os.path.isdir(d):
        raise sur.SurrogateError("no SG13G2 ngspice models under %s (set PDK_ROOT)" % d)
    return d


def lib_sh(fn, *args):
    """Call a sim/lib.sh awk extractor (the same code the pilot used)."""
    r = sh(["bash", "-c", 'source "$1"; shift; "$@"', "_", os.path.join(REPO, "sim/lib.sh"), fn] + list(args))
    if r.returncode != 0:
        raise sur.SurrogateError("sim/lib.sh %s failed: %s" % (fn, r.stderr.strip()))
    return r.stdout.split()


def render_deck(series, topology, vctrl, temp_c, mdir, out_prefix):
    with open(os.path.join(REPO, "design/vco.spice")) as fh:
        body = sur.surrogate_vco_body(fh.read(), "sg13_hv_svaricap_sur", topology)
    body, n = re.subn(r"(?m)^VCT VCTRL 0 dc \S+$", "VCT VCTRL 0 dc %s" % vctrl, body)
    if n != 1:
        raise sur.SurrogateError("expected exactly one VCT source in design/vco.spice, found %d" % n)
    with open(os.path.join(REPO, IND_MODEL)) as fh:
        ind = fh.read()
    return "\n".join([
        "* surrogate_bench: %s   %s" % (sur.LABEL, topology),
        "* GENERATED by sim/oscillator-core/surrogate_bench.py (issue #179); the 32 OSDI",
        "* sg13_hv_svaricap cells of design/vco.spice are replaced by sim/tools/svaricap_surrogate.py",
        ".lib %s/cornerHBT.lib hbt_typ" % mdir,
        ".lib %s/cornerCAP.lib cap_typ" % mdir,
        "* inductor model (inlined): " + IND_MODEL,
        ind,
        "* dsubw card: v0.3.0 text with only vj 0.1 -> 0.3357 (svaricap_overlay.py)",
        sur.render_model_card(),
        sur.render_subckt(series),
        body,
        ".temp %g" % temp_c,
        "Bvdiff VDIFF 0 V = V(OUTP) - V(OUTN)",
        "Rvdiff VDIFF 0 1G",
        ".ic v(OUTP)=3.305 v(OUTN)=3.295",
        ".control",
        "save v(VDIFF) v(OUTP) v(OUTN) v(VCTRL) v(xcvp1.nc) v(xcvp16.nc) v(xcvn1.nc) v(xcvn16.nc)",
        "op",
        "tran %s %s 0 %s" % (TSTEP, TSTOP, TMAX),
        "let w1 = v(VDIFF)",
        "wrdata %s_vdiff w1" % out_prefix,
        "* v_rec at the behavioral core = V(core node) - V(G); G = VCTRL",
        "let w2 = v(xcvp1.nc) - v(VCTRL)",
        "wrdata %s_vrec_p1 w2" % out_prefix,
        "let w3 = v(xcvp16.nc) - v(VCTRL)",
        "wrdata %s_vrec_p16 w3" % out_prefix,
        "let w4 = v(xcvn1.nc) - v(VCTRL)",
        "wrdata %s_vrec_n1 w4" % out_prefix,
        "let w5 = v(xcvn16.nc) - v(VCTRL)",
        "wrdata %s_vrec_n16 w5" % out_prefix,
        ".endc",
        ".end", ""])


class TraceError(Exception):
    """A probe waveform is malformed or incomplete (a failed MEASUREMENT).  This is
    distinct from a valid waveform outside the characterized voltage domain
    (INVALID-OUT-OF-DOMAIN, exit 3).  Never publishes f_osc / amplitude (exit 2)."""


# Coverage / grid tolerances, tied to the bench's own transient settings.  The
# deck runs `tran TSTEP TSTOP 0 TMAX`, so ngspice never takes a step above TMAX:
# the first sample must lie within TMAX of t = 0, the last within TMAX of TSTOP,
# and no gap may exceed 2*TMAX (a dropped row would otherwise hide a stretch of
# the run from the whole-run domain decision).
TMAX_S = 2e-12
COVER_TOL_S = TMAX_S
MAX_GAP_S = 2 * TMAX_S
GRID_TOL_S = 1e-3 * TMAX_S  # probe time grids come from one transient: must agree


def read_trace(path, t_stop=TSTOP_S, cover_tol=COVER_TOL_S, max_gap=MAX_GAP_S):
    """Read and fully validate one `wrdata` trace: (times, values).

    Every nonblank row must be exactly `time value`, both finite floats (overflow
    such as 1e999 is inf and rejected); times strictly increasing; coverage of
    [0, t_stop] within cover_tol with no gap above max_gap.  Validation happens
    on every sample BEFORE any min/max reduction (min/max silently skip NaN)."""
    ts, vs = [], []
    with open(path) as fh:
        for n, ln in enumerate(fh, 1):
            f = ln.split()
            if not f:
                continue
            if len(f) != 2:
                raise TraceError("%s:%d: malformed row (%d fields, expected 2)" % (path, n, len(f)))
            try:
                t, v = float(f[0]), float(f[1])
            except ValueError:
                raise TraceError("%s:%d: non-numeric row %r" % (path, n, ln.strip()))
            if not (math.isfinite(t) and math.isfinite(v)):
                raise TraceError("%s:%d: non-finite sample (t=%r, v=%r)" % (path, n, f[0], f[1]))
            if ts and not t > ts[-1]:
                raise TraceError("%s:%d: time not strictly increasing (%r after %r)" % (path, n, t, ts[-1]))
            if ts and t - ts[-1] > max_gap:
                raise TraceError("%s:%d: gap %.3g s exceeds %.3g s (missing rows)" % (path, n, t - ts[-1], max_gap))
            ts.append(t)
            vs.append(v)
    if not ts:
        raise TraceError("%s: empty trace" % path)
    if ts[0] > cover_tol:
        raise TraceError("%s: trace starts at %.3g s, after the %.3g s coverage tolerance" % (path, ts[0], cover_tol))
    if ts[-1] < t_stop - cover_tol:
        raise TraceError("%s: trace ends at %.3g s, short of %.3g s by more than %.3g s (truncated)"
                         % (path, ts[-1], t_stop, cover_tol))
    return ts, vs


def trace_extrema(path):
    """(min, max, n) of a validated trace; raises TraceError, never skips samples."""
    _ts, vs = read_trace(path)
    return min(vs), max(vs), len(vs)


def check_common_grid(grids, tol=GRID_TOL_S):
    """All probe traces come from one transient and must share one time grid."""
    ref_name, ref = grids[0]
    for name, ts in grids[1:]:
        if len(ts) != len(ref) or any(abs(a - b) > tol for a, b in zip(ts, ref)):
            raise TraceError("time grid of %s differs from %s (%d vs %d samples)"
                             % (name, ref_name, len(ts), len(ref)))


def validated_vrec_extrema(prefix):
    """Validate vdiff and the four v_rec probes, check grid consistency, and return
    the whole-run (vmin, vmax).  Raises TraceError on any invalid measurement."""
    grids, ex = [], []
    for k in ("vdiff", "vrec_p1", "vrec_p16", "vrec_n1", "vrec_n16"):
        ts, vs = read_trace("%s_%s" % (prefix, k))
        grids.append((k, ts))
        if k != "vdiff":
            ex.append((min(vs), max(vs)))
    check_common_grid(grids)
    return min(e[0] for e in ex), max(e[1] for e in ex)


def git_info():
    head = sh(["git", "-C", REPO, "rev-parse", "HEAD"]).stdout.strip()
    dirty = sh(["git", "-C", REPO, "diff", "--quiet", "HEAD", "--",
                "sim/tools", "sim/oscillator-core/surrogate_bench.py", "design",
                "sim/varactor-characterization/records"]).returncode != 0
    return head, dirty


def ngspice_version():
    out = sh(["ngspice", "-v"]).stdout
    m = re.search(r"ngspice-(\S+)", out)
    return m.group(0) if m else "unknown"


# --- evidence ownership (issue #191) -------------------------------------------
# Records are append-only evidence.  Before anything is published the bench
# reserves a record id through the shared sim/lib.sh reserve_record_id helper
# (an exclusive mkdir of <root>/corners/<id>, the same namespace every runner
# in this experiment uses), keeps the point in the basename AFTER the reserved
# id, and then publishes with exclusive creation only, so even a misconfigured
# reservation can never truncate an existing artifact.
LIB_SH = os.path.join(REPO, "sim", "lib.sh")
RESERVE_ATTEMPTS = 50


class PublicationError(sur.SurrogateError):
    """Evidence ownership could not be established or publication would clobber
    an existing artifact.  Raised BEFORE / INSTEAD OF any evidence write."""


def reservation_root(records_dir):
    """Directory passed to reserve_record_id as <experiment_dir>: the parent of
    the records dir.  In the standard layout (<R>/records + <R>/netlist-snapshots,
    default <R> = this experiment) that is <R>, so the id comes from the same
    <R>/corners namespace every runner here uses and the helper's own collision
    checks cover both output locations.  For a custom layout the custom records
    and snapshots dirs are additionally checked by reserve_publication, and
    publish() creates exclusively, so a custom dir cannot bypass collision
    detection."""
    return os.path.dirname(os.path.realpath(records_dir))


def _reserve_id(root, first):
    """One call to the shared helper; returns the reserved id (raises on failure)."""
    env = dict(os.environ)
    if not first:
        env.pop("SIM_RECORD_SUFFIX", None)  # test hook honoured on the first call only
    r = subprocess.run(["bash", "-c", 'source "$1" && reserve_record_id "$2" "$3"', "_",
                        LIB_SH, REPO, root], capture_output=True, text=True, env=env)
    rid = r.stdout.strip()
    if r.returncode != 0 or not re.match(r"^[0-9]{8}-[0-9]{6}-[0-9A-Za-z]+-[0-9a-f]+$", rid):
        raise PublicationError("record id reservation failed under %s (rc=%d): %s"
                               % (root, r.returncode, (r.stderr.strip() or rid or "no id printed")))
    return rid


def _taken(records_dir, snapshots_dir, rid):
    return (glob.glob(os.path.join(glob.escape(records_dir), glob.escape(rid) + "*"))
            or glob.glob(os.path.join(glob.escape(snapshots_dir), glob.escape(rid) + "*")))


def reserve_publication(records_dir, snapshots_dir, point):
    """Reserve an id and return the publication paths it owns.

    Nothing under records_dir / snapshots_dir is created here.  Raises
    PublicationError if no id can be reserved."""
    records_dir = os.path.abspath(records_dir)
    snapshots_dir = os.path.abspath(snapshots_dir)
    root = reservation_root(records_dir)
    for attempt in range(RESERVE_ATTEMPTS):
        rid = _reserve_id(root, attempt == 0)
        if _taken(records_dir, snapshots_dir, rid):
            continue  # custom output dir already holds evidence under this id; never reuse it
        base = "%s-surrogate-%s" % (rid, point)
        snap = os.path.join(snapshots_dir, base)
        return {"reserved_id": rid, "record_id": base, "root": root,
                "md": os.path.join(records_dir, base + ".md"),
                "csv": os.path.join(records_dir, base + ".csv"),
                "snap": snap,
                "deck": os.path.join(snap, "surrogate_%s.spice" % point),
                "log": os.path.join(snap, "surrogate_%s.log" % point)}
    raise PublicationError("could not reserve a record id free in %s and %s after %d attempts"
                           % (records_dir, snapshots_dir, RESERVE_ATTEMPTS))


def publish(paths, deck_bytes, log_bytes, md_text, fields):
    """Publish the evidence with exclusive creation only (O_EXCL / non-`-p` mkdir).

    If any destination already exists nothing is overwritten: the files this
    call itself created are removed again and PublicationError is raised."""
    for k in ("snap", "deck", "log", "md", "csv"):
        if os.path.lexists(paths[k]):
            raise PublicationError("refusing to overwrite existing evidence: %s" % paths[k])
    made = []
    try:
        os.makedirs(os.path.dirname(paths["md"]), exist_ok=True)
        os.makedirs(os.path.dirname(paths["snap"]), exist_ok=True)
        os.mkdir(paths["snap"])
        made.append(paths["snap"])
        for k, data in (("deck", deck_bytes), ("log", log_bytes), ("md", md_text.encode())):
            with open(paths[k], "xb") as fh:
                made.append(paths[k])
                fh.write(data)
        with open(paths["csv"], "x", newline="") as fh:
            made.append(paths["csv"])
            w = csv.DictWriter(fh, fieldnames=list(fields))
            w.writeheader()
            w.writerow(fields)
    except FileExistsError as e:
        for p in reversed(made):
            (os.rmdir if os.path.isdir(p) else os.unlink)(p)
        raise PublicationError("refusing to overwrite existing evidence: %s" % e.filename)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--point", required=True, choices=("pre79", "corrected"))
    ap.add_argument("--vctrl", type=float, default=1.65)
    ap.add_argument("--corner", default="tt")
    ap.add_argument("--temp", type=float, default=27.0)
    ap.add_argument("--records-dir", default=os.path.join(HERE, "records"))
    ap.add_argument("--snapshots-dir", default=os.path.join(HERE, "netlist-snapshots"))
    ap.add_argument("--allow-dirty", action="store_true")
    ap.add_argument("--dry-run", action="store_true", help="print tolerances and the deck path only")
    a = ap.parse_args(argv)

    series = sur.load_series(os.path.join(REPO, sur.DEFAULT_CSV))[(a.corner, a.temp)]
    tol = series.tolerances()
    prov = sur.source_provenance()
    head, dirty = git_info()
    if dirty and not a.allow_dirty:
        raise sur.SurrogateError("uncommitted changes under sim/tools, design, the bench or the source CSV; "
                                 "commit first so the record's commit is meaningful (or --allow-dirty)")

    # --- predeclare tolerances BEFORE any simulation -------------------------
    with open(os.path.join(REPO, PILOT_CSV), newline="") as fh:
        pilot = [r for r in csv.DictReader(fh) if r["corner_id"] == PILOT_ROW]
    if len(pilot) != 1:
        raise sur.SurrogateError("pilot row %s not found exactly once" % PILOT_ROW)
    pilot = pilot[0]
    pilot_q = float(pilot["quant_floor_interp_pct"])
    print("predeclared (before the simulator starts): series %s epsilon_C=%.6g epsilon_R=%.6g"
          % (series.key, tol["epsilon_C"], tol["epsilon_R"]))
    print("  tol_dqdv=%.6g tol_R=%.6g; pilot quant_floor_interp_pct=%.6g"
          % (tol["tol_dqdv"], tol["tol_R"], pilot_q))

    # DC pre-check: refuse before simulating if even the DC point is outside the domain
    v0 = sur.vrec_from_vctrl_dc(a.vctrl)
    if sur.classify_domain(v0, v0) != sur.STATUS_OK:
        print(sur.STATUS_INVALID + ": DC v_rec = %g V" % v0, file=sys.stderr)
        return 3

    work = tempfile.mkdtemp(prefix="sur179-")  # scratch only; never published in place
    prefix = os.path.join(work, "w")
    deck = render_deck(series, a.point, a.vctrl, a.temp, models_dir(), prefix)
    deck_path = os.path.join(work, "deck.spice")
    with open(deck_path, "w") as fh:
        fh.write(deck)
    shutil.copy(os.path.join(HERE, ".spiceinit"), os.path.join(work, ".spiceinit"))
    if a.dry_run:
        print("deck:", deck_path)
        return 0

    # --- reserve evidence ownership BEFORE the simulator starts (issue #191) --
    try:
        out = reserve_publication(a.records_dir, a.snapshots_dir, a.point)
    except PublicationError:
        shutil.rmtree(work, ignore_errors=True)
        raise
    rid = out["record_id"]
    print("reserved record id %s (namespace %s)" % (out["reserved_id"], os.path.join(out["root"], "corners")))

    cmd = ["ngspice", "-b", "deck.spice"]
    r = subprocess.run(cmd, cwd=work, capture_output=True, text=True)
    log = r.stdout + r.stderr
    with open(os.path.join(work, "ngspice.log"), "w") as fh:
        fh.write(log)
    bad = re.search(r"(?im)^.*(unknown subckt|could not find|fatal|doAnalyses: .*(error|aborted)|"
                    r"no such vector|Error:).*$", log)
    if r.returncode != 0 or bad:
        print("ngspice failed (rc=%d): %s" % (r.returncode, bad.group(0) if bad else ""), file=sys.stderr)
        print("scratch kept at", work, file=sys.stderr)
        return 2

    # --- domain: instantaneous v_rec extrema over the WHOLE run ---------------
    try:
        vmin, vmax = validated_vrec_extrema(prefix)
    except TraceError as e:
        print("invalid measurement (NOT out-of-domain; no f_osc / amplitude published): %s" % e, file=sys.stderr)
        print("scratch kept at", work, file=sys.stderr)
        return 2
    status = sur.classify_domain(vmin, vmax)

    deck_sha = sha256_bytes(deck.encode())
    ver = ngspice_version()

    fields = {"record_id": rid, "point": a.point, "label": sur.LABEL, "status": status,
              "v_rec_min_v": "%.6f" % vmin, "v_rec_max_v": "%.6f" % vmax}
    md = ["# Record %s" % rid, "", "**%s**" % sur.LABEL, "",
          "- **Experiment**: oscillator-core, OSDI-free varactor surrogate (issue #179), point `%s`" % a.point,
          "- **Topology**: " + ("pre-#79 (`bn` tied to each cell's own well W)" if a.point == "pre79"
                                else "corrected (`bn` on 0, as design/vco.spice)"),
          "- **Corner**: MOS fit series `%s/%g C`, cap_typ, hbt_typ, VCTRL = %g V, VDD 3.3 V" % (a.corner, a.temp, a.vctrl),
          "- **Surrogate source**: `%s` (sha256 `%s`, last commit touching it `%s`), mos/small rows, "
          "`c_5ghz_f` and `q_5ghz` columns" % (prov["csv"], prov["csv_sha256"], prov["csv_commit"]),
          "- **Code commit**: `%s`%s" % (head, " (dirty tree, --allow-dirty)" if dirty else ""),
          "- **Command**: `sim/oscillator-core/surrogate_bench.py --point %s --vctrl %g --corner %s --temp %g`; "
          "inner simulator command `%s` (single unit, local)" % (a.point, a.vctrl, a.corner, a.temp, " ".join(cmd)),
          "- **Simulator**: `%s`; transient `tran %s %s 0 %s`, window %g..%g s, start `.ic` 10 mV differential"
          % (ver, TSTEP, TSTOP, TMAX, TMEAS_START, TSTOP_S),
          "- **Rendered deck**: `netlist-snapshots/%s/surrogate_%s.spice` (sha256 `%s`)" % (rid, a.point, deck_sha),
          "- **Model**: charge-based behavioral MOS core (piecewise-linear C, exact piecewise-quadratic "
          "q), pointwise series R = 1/(2 pi 5e9 C Q), exactly one native `dsubw`+`rsubw` branch per cell "
          "with the sanctioned `vj = 0.3357` overlay (`sim/tools/svaricap_overlay.py`); contract in "
          "`sim/tools/svaricap_surrogate.py`.",
          "- " + sur.NOISE_NOTE,
          "- " + sur.PATH_NOTE,
          "- " + sur.FOLLOW_ON_NOTE,
          "- **Limits**: 5 GHz effective C/Q only; fitted bias/corner/temperature/geometry only; "
          "one probe cell per side pair (cells 1 and 16 on each side) stands for the 16 identical cells "
          "of that side; this smoke does not establish broadband or large-grid accuracy.",
          "- **Estimator**: sim/lib.sh `osc_metrics` on V(OUTP)-V(OUTN), rising crossings through the "
          "window mean, interpolated; quantization floor reported per point.",
          "- **Instantaneous v_rec at the core** (whole run, 4 probe cells): min %.6f V, max %.6f V; "
          "domain [0.0, 3.3] V +/- 1 mV -> **%s**" % (vmin, vmax, status), ""]

    rc = 0
    if status != sur.STATUS_OK:
        md += ["## Result", "", "**INVALID-OUT-OF-DOMAIN** -- the surrogate was driven outside its characterized "
               "0.0-3.3 V interval. It refuses to extrapolate: no f_osc / amplitude is reported for this run.", ""]
        rc = 3
    else:
        m = lib_sh("osc_metrics", prefix + "_vdiff", repr(TMEAS_START), repr(TSTOP_S))
        f, vpp, cycles, _av, _x1, _xn, dtmax, nsamp = (float(x) for x in m)
        q_interp = dtmax * f / cycles * 100.0 if cycles else float("nan")
        q_count = 100.0 / cycles if cycles else float("nan")
        st = lib_sh("osc_settle", prefix + "_vdiff", repr(SETTLE_FRAC), repr(TMEAS_START))
        t_settle = st[0]
        fields.update({"f_osc_hz": "%.6e" % f, "vpp_diff_v": "%.6e" % vpp, "cycles": "%d" % cycles,
                       "dt_max_s": "%.3e" % dtmax, "quant_floor_interp_pct": "%.6g" % q_interp,
                       "quant_floor_count_pct": "%.6g" % q_count, "t_settle_s": t_settle})
        started = f > 0 and cycles >= 3
        md += ["## Result", "",
               "- starts and oscillates: **%s**" % ("YES" if started else "NO"),
               "- f_osc = %.6e Hz (%d cycles, interpolated quantization floor %.4g %%, "
               "no-interpolation floor %.4g %%)" % (f, cycles, q_interp, q_count),
               "- differential Vpp = %.6e V; startup settling (0.9 of final envelope) t_settle = %s s"
               % (vpp, t_settle), ""]
        if not started:
            rc = 1
        if a.point == "pre79":
            fp, ap_ = float(pilot["f_osc_hz"]), float(pilot["vpp_diff_v"])
            q_used = max(pilot_q, q_interp)
            kt = sur.known_answer_tolerances(tol["epsilon_C"], tol["epsilon_R"], q_used)
            rf = abs(f - fp) / fp
            ra = abs(vpp - ap_) / ap_
            ok = started and rf <= kt["tol_freq"] and ra <= kt["tol_amp"]
            fields.update({"pilot_f_osc_hz": "%.6e" % fp, "pilot_vpp_diff_v": "%.6e" % ap_,
                           "epsilon_C": "%.6g" % tol["epsilon_C"], "epsilon_R": "%.6g" % tol["epsilon_R"],
                           "quant_floor_used_pct": "%.6g" % q_used,
                           "tol_freq": "%.6g" % kt["tol_freq"], "tol_amp": "%.6g" % kt["tol_amp"],
                           "resid_freq": "%.6g" % rf, "resid_amp": "%.6g" % ra,
                           "known_answer": "PASS" if ok else "FAIL"})
            md += ["## Known-answer comparison against the pilot (fixed formulas of issue #179)", "",
                   "Pilot row `%s` in `%s` (old OSDI netlist, vj = 0.1 unpatched card, pre-#79 topology)." % (PILOT_ROW, PILOT_CSV), "",
                   "| quantity | pilot | surrogate | relative residual | fixed tolerance | verdict |",
                   "|---|---|---|---|---|---|",
                   "| f_osc (Hz) | %.6e | %.6e | %.4f %% | %.4f %% | %s |" % (fp, f, 100 * rf, 100 * kt["tol_freq"], "ok" if rf <= kt["tol_freq"] else "EXCEEDED"),
                   "| differential Vpp (V) | %.6e | %.6e | %.4f %% | %.4f %% | %s |" % (ap_, vpp, 100 * ra, 100 * kt["tol_amp"], "ok" if ra <= kt["tol_amp"] else "EXCEEDED"),
                   "",
                   "Tolerance inputs (computed before the run; leave-one-out on the %s series): "
                   "epsilon_C = %.6g, epsilon_R = %.6g; frequency tolerance = max(1 %%, epsilon_C/2 + "
                   "quant_floor_interp_pct/100) with quant_floor_interp_pct = max(pilot %.6g, this run %.6g) = %.6g; "
                   "amplitude tolerance = max(5 %%, epsilon_C + epsilon_R)."
                   % (series.key, tol["epsilon_C"], tol["epsilon_R"], pilot_q, q_interp, q_used), "",
                   "**Known-answer verdict: %s.** The formulas are fixed by the issue and were not "
                   "widened or tuned after seeing this result." % ("PASS" if ok else "FAIL"), ""]
            if not ok:
                rc = 1
        else:
            md += ["This is the corrected-topology (`bn` on 0) smoke point. It proves startup and model "
                   "integration only and is not compared with the pre-#79 frequency.", ""]

    fields["label"] = sur.LABEL
    with open(deck_path, "rb") as fh:
        deck_bytes = fh.read()
    with open(os.path.join(work, "ngspice.log"), "rb") as fh:
        log_bytes = fh.read()
    try:
        publish(out, deck_bytes, log_bytes, "\n".join(md), fields)
    except PublicationError as e:
        print("publication refused (nothing overwritten): %s" % e, file=sys.stderr)
        print("scratch kept at", work, file=sys.stderr)
        raise
    shutil.rmtree(work, ignore_errors=True)
    print("record:", out["md"])
    print({k: fields[k] for k in fields if k not in ("label",)})
    return rc


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except sur.SurrogateError as e:
        print("surrogate_bench: refused: %s" % e, file=sys.stderr)
        sys.exit(1)
